spring:
  profiles: default
server:
  port: 3001 #${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/