zuul:
server:
  port: 3000 #${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
ribbon:
  eager-load:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
